version: "3"
services:
    # NOTE: In case you cant pull from GHCR uncomment this block.
    #
    #unit-test-robot-server-local:
    #  build:
    #    context: ./robot-server
    #    dockerfile: Dockerfile.tests

    robot-server-local:
      build:
        context: ./robot-server
      ports:
        - "5000:5000"
      environment:
        - FLASK_APP=app.py
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_RUN_PORT=5000
        - FLASK_ENV=development
        - POSTGRES_DB=dev
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
      # - unit-test-robot-server-local
        - postgres

    #robot-server-ghcr:
    #  image: "ghcr.io/deathfireofdoom/robot-vacuum:0.0.4"
    #  ports:
    #    - "5000:5000"
    #  environment:
    #    - FLASK_APP=app.py
    #    - FLASK_RUN_HOST=0.0.0.0
    #    - FLASK_RUN_PORT=5000
    #    - FLASK_ENV=development
    #    - POSTGRES_DB=dev
    #    - POSTGRES_HOST=postgres
    #    - POSTGRES_PORT=5432
    #    - POSTGRES_USER=postgres
    #    - POSTGRES_PASSWORD=postgres
    #  depends_on:
    #    - postgres 
      
    postgres:
      image: "postgres:latest"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=dev
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
